# Generated by Django 5.1.5 on 2025-01-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_pago_plan_alter_pago_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Completado'), (3, 'Fallido')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tarjeta de Crédito/Débito'), (2, 'PayPal'), (3, 'Transferencia Bancaria')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
