# Generated by Django 5.1.5 on 2025-01-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_membresia',
            field=models.CharField(choices=[(1, 'Básico'), (2, 'Premium'), (3, 'VIP')], default=1),
        ),
    ]
