# Generated by Django 5.1.5 on 2025-01-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_plan_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan_membresia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Premium'), (3, 'VIP')], default=1),
        ),
    ]
