# Generated by Django 5.1.5 on 2025-01-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        ('users', '0005_alter_user_plan_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan_membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='memberships.membership'),
        ),
    ]
