# Generated by Django 5.1.5 on 2025-01-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
