# Generated by Django 5.1.5 on 2025-01-27 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_asistencia_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
