# Generated by Django 5.1.5 on 2025-01-26 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0004_alter_clase_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('frecuencia', models.CharField(max_length=50)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.clase')),
            ],
        ),
    ]
