# Generated by Django 5.1.5 on 2025-01-26 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_clase_is_active_reserva_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='horario',
        ),
        migrations.AddField(
            model_name='clase',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='clase',
            name='hora',
            field=models.TimeField(default='09:00'),
        ),
    ]
