# Generated by Django 5.1.5 on 2025-01-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_clase_horario_clase_fecha_clase_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='hora',
            field=models.CharField(max_length=5),
        ),
    ]
